//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsumingWebService.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Sum", ReplyAction="*")]
        int Sum(int x, int y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Sum", ReplyAction="*")]
        System.Threading.Tasks.Task<int> SumAsync(int x, int y);
        
        // CODEGEN: Generating message contract since the wrapper name (Sum_x0020_of_x0020_Floats) of message Sum_x0020_of_x0020_Floats does not match the default value (Sum1)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Sum of Floats", ReplyAction="*")]
        ConsumingWebService.ServiceReference1.SumofFloats1 Sum1(ConsumingWebService.ServiceReference1.SumofFloats request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Sum of Floats", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsumingWebService.ServiceReference1.SumofFloats1> Sum1Async(ConsumingWebService.ServiceReference1.SumofFloats request);
        
        // CODEGEN: Generating message contract since the wrapper name (Product_x0020_of_x0020_Numbers) of message Product_x0020_of_x0020_Numbers does not match the default value (Products)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Product of Numbers", ReplyAction="*")]
        ConsumingWebService.ServiceReference1.ProductofNumbers1 Products(ConsumingWebService.ServiceReference1.ProductofNumbers request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Product of Numbers", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsumingWebService.ServiceReference1.ProductofNumbers1> ProductsAsync(ConsumingWebService.ServiceReference1.ProductofNumbers request);
        
        // CODEGEN: Generating message contract since the wrapper name (Division_x0020_of_x0020_Numbers) of message Division_x0020_of_x0020_Numbers does not match the default value (Divisions)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Division of Numbers", ReplyAction="*")]
        ConsumingWebService.ServiceReference1.DivisionofNumbers1 Divisions(ConsumingWebService.ServiceReference1.DivisionofNumbers request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Division of Numbers", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsumingWebService.ServiceReference1.DivisionofNumbers1> DivisionsAsync(ConsumingWebService.ServiceReference1.DivisionofNumbers request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Sum of Floats", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SumofFloats {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public float x;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public float y;
        
        public SumofFloats() {
        }
        
        public SumofFloats(float x, float y) {
            this.x = x;
            this.y = y;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Sum of FloatsResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SumofFloats1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Sum_x0020_of_x0020_FloatsResult", Namespace="http://tempuri.org/", Order=0)]
        public float SumofFloatsResult;
        
        public SumofFloats1() {
        }
        
        public SumofFloats1(float SumofFloatsResult) {
            this.SumofFloatsResult = SumofFloatsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Product of Numbers", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ProductofNumbers {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public float x;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public float y;
        
        public ProductofNumbers() {
        }
        
        public ProductofNumbers(float x, float y) {
            this.x = x;
            this.y = y;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Product of NumbersResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ProductofNumbers1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Product_x0020_of_x0020_NumbersResult", Namespace="http://tempuri.org/", Order=0)]
        public float ProductofNumbersResult;
        
        public ProductofNumbers1() {
        }
        
        public ProductofNumbers1(float ProductofNumbersResult) {
            this.ProductofNumbersResult = ProductofNumbersResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Division of Numbers", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DivisionofNumbers {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public float x;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public float y;
        
        public DivisionofNumbers() {
        }
        
        public DivisionofNumbers(float x, float y) {
            this.x = x;
            this.y = y;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Division of NumbersResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DivisionofNumbers1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Division_x0020_of_x0020_NumbersResult", Namespace="http://tempuri.org/", Order=0)]
        public float DivisionofNumbersResult;
        
        public DivisionofNumbers1() {
        }
        
        public DivisionofNumbers1(float DivisionofNumbersResult) {
            this.DivisionofNumbersResult = DivisionofNumbersResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : ConsumingWebService.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<ConsumingWebService.ServiceReference1.WebService1Soap>, ConsumingWebService.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int Sum(int x, int y) {
            return base.Channel.Sum(x, y);
        }
        
        public System.Threading.Tasks.Task<int> SumAsync(int x, int y) {
            return base.Channel.SumAsync(x, y);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsumingWebService.ServiceReference1.SumofFloats1 ConsumingWebService.ServiceReference1.WebService1Soap.Sum1(ConsumingWebService.ServiceReference1.SumofFloats request) {
            return base.Channel.Sum1(request);
        }
        
        public float Sum1(float x, float y) {
            ConsumingWebService.ServiceReference1.SumofFloats inValue = new ConsumingWebService.ServiceReference1.SumofFloats();
            inValue.x = x;
            inValue.y = y;
            ConsumingWebService.ServiceReference1.SumofFloats1 retVal = ((ConsumingWebService.ServiceReference1.WebService1Soap)(this)).Sum1(inValue);
            return retVal.SumofFloatsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsumingWebService.ServiceReference1.SumofFloats1> ConsumingWebService.ServiceReference1.WebService1Soap.Sum1Async(ConsumingWebService.ServiceReference1.SumofFloats request) {
            return base.Channel.Sum1Async(request);
        }
        
        public System.Threading.Tasks.Task<ConsumingWebService.ServiceReference1.SumofFloats1> Sum1Async(float x, float y) {
            ConsumingWebService.ServiceReference1.SumofFloats inValue = new ConsumingWebService.ServiceReference1.SumofFloats();
            inValue.x = x;
            inValue.y = y;
            return ((ConsumingWebService.ServiceReference1.WebService1Soap)(this)).Sum1Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsumingWebService.ServiceReference1.ProductofNumbers1 ConsumingWebService.ServiceReference1.WebService1Soap.Products(ConsumingWebService.ServiceReference1.ProductofNumbers request) {
            return base.Channel.Products(request);
        }
        
        public float Products(float x, float y) {
            ConsumingWebService.ServiceReference1.ProductofNumbers inValue = new ConsumingWebService.ServiceReference1.ProductofNumbers();
            inValue.x = x;
            inValue.y = y;
            ConsumingWebService.ServiceReference1.ProductofNumbers1 retVal = ((ConsumingWebService.ServiceReference1.WebService1Soap)(this)).Products(inValue);
            return retVal.ProductofNumbersResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsumingWebService.ServiceReference1.ProductofNumbers1> ConsumingWebService.ServiceReference1.WebService1Soap.ProductsAsync(ConsumingWebService.ServiceReference1.ProductofNumbers request) {
            return base.Channel.ProductsAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsumingWebService.ServiceReference1.ProductofNumbers1> ProductsAsync(float x, float y) {
            ConsumingWebService.ServiceReference1.ProductofNumbers inValue = new ConsumingWebService.ServiceReference1.ProductofNumbers();
            inValue.x = x;
            inValue.y = y;
            return ((ConsumingWebService.ServiceReference1.WebService1Soap)(this)).ProductsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsumingWebService.ServiceReference1.DivisionofNumbers1 ConsumingWebService.ServiceReference1.WebService1Soap.Divisions(ConsumingWebService.ServiceReference1.DivisionofNumbers request) {
            return base.Channel.Divisions(request);
        }
        
        public float Divisions(float x, float y) {
            ConsumingWebService.ServiceReference1.DivisionofNumbers inValue = new ConsumingWebService.ServiceReference1.DivisionofNumbers();
            inValue.x = x;
            inValue.y = y;
            ConsumingWebService.ServiceReference1.DivisionofNumbers1 retVal = ((ConsumingWebService.ServiceReference1.WebService1Soap)(this)).Divisions(inValue);
            return retVal.DivisionofNumbersResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsumingWebService.ServiceReference1.DivisionofNumbers1> ConsumingWebService.ServiceReference1.WebService1Soap.DivisionsAsync(ConsumingWebService.ServiceReference1.DivisionofNumbers request) {
            return base.Channel.DivisionsAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsumingWebService.ServiceReference1.DivisionofNumbers1> DivisionsAsync(float x, float y) {
            ConsumingWebService.ServiceReference1.DivisionofNumbers inValue = new ConsumingWebService.ServiceReference1.DivisionofNumbers();
            inValue.x = x;
            inValue.y = y;
            return ((ConsumingWebService.ServiceReference1.WebService1Soap)(this)).DivisionsAsync(inValue);
        }
    }
}
